name: counter_multiply_by_10
description: A Flutter application that multiplies a counter by 10 using the Cubit pattern for state management.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  bloc: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.0.0
  mocktail: ^0.1.0

flutter:
  uses-material-design: true